"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpenText, Loader2 } from "lucide-react";
import { calculateStats, hasEveryTag } from "@/lib/stats";
import type { Stats, Tag, Trade, TradeMode } from "@/lib/types";
import { MetricCard } from "@/components/metric-card";

const format = (value: number, suffix = "") => `${value.toFixed(2)}${suffix}`;
const pf = (value: number | null) => value === null ? "∞" : value.toFixed(2);

function TagChooser({ tags, value, onChange }: { tags: Tag[]; value: string[]; onChange: (ids: string[]) => void }) {
  return <div className="flex flex-wrap gap-2">{tags.map((tag) => <button type="button" key={tag.id} onClick={() => onChange(value.includes(tag.id) ? value.filter((id) => id !== tag.id) : [...value, tag.id])} className={`chip py-1.5 ${value.includes(tag.id) ? "chip-active" : ""}`}>{tag.name}</button>)}</div>;
}

function ComparisonStats({ stats }: { stats: Stats }) {
  return <div className="grid grid-cols-2 gap-x-6 gap-y-4 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-6">{[["Trades", String(stats.trades)], ["Kein Trade", String(stats.noTrades)], ["Winrate", format(stats.winrate, "%")], ["Avg R", format(stats.avgR, "R")], ["Expectancy", format(stats.expectancy, "R")], ["Profit Factor", pf(stats.profitFactor)]].map(([label,value]) => <div key={label}><span className="label">{label}</span><p className="text-lg font-bold tabular-nums">{value}</p></div>)}</div>;
}

export function AnalysisDashboard() {
  const [trades, setTrades] = useState<Trade[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [tradeMode, setTradeMode] = useState<TradeMode>("backtest");
  const [selected, setSelected] = useState<string[]>([]); const [groupA, setGroupA] = useState<string[]>([]); const [groupB, setGroupB] = useState<string[]>([]);
  useEffect(() => { Promise.all([fetch("/api/trades"), fetch("/api/tags")]).then(async ([a,b]) => { const tradeData = await a.json(); const tagData = await b.json(); if (!a.ok) throw new Error(tradeData.error); if (!b.ok) throw new Error(tagData.error); setTrades(tradeData.trades); setTags(tagData.tags); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Analyse konnte nicht geladen werden.")).finally(() => setLoading(false)); }, []);

  const modeTrades = useMemo(() => trades.filter((trade) => trade.trade_mode === tradeMode), [trades, tradeMode]);
  const filtered = useMemo(() => modeTrades.filter((trade) => hasEveryTag(trade, selected)), [modeTrades, selected]);
  const stats = useMemo(() => calculateStats(filtered), [filtered]);
  const tagStats = useMemo(() => tags.map((tag) => ({ tag, stats: calculateStats(modeTrades.filter((trade) => hasEveryTag(trade, [tag.id]))) })).filter((row) => row.stats.trades + row.stats.noTrades > 0).sort((a,b) => (b.stats.trades + b.stats.noTrades) - (a.stats.trades + a.stats.noTrades)), [modeTrades, tags]);
  const statsA = useMemo(() => calculateStats(modeTrades.filter((trade) => hasEveryTag(trade, groupA))), [modeTrades, groupA]);
  const statsB = useMemo(() => calculateStats(modeTrades.filter((trade) => hasEveryTag(trade, groupB))), [modeTrades, groupB]);
  const reviewedTrades = useMemo(() => filtered.filter((trade) => trade.review_observation || trade.review_mistake || trade.review_invalidation || trade.review_illogical), [filtered]);

  function changeTradeMode(value: TradeMode) {
    setTradeMode(value);
    setSelected([]);
    setGroupA([]);
    setGroupB([]);
  }

  if (loading) return <div className="panel flex min-h-72 items-center justify-center text-sm text-zinc-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Analyse wird berechnet</div>;
  if (error) return <div className="panel p-5 sm:p-8"><p className="text-sm font-semibold">Supabase-Verbindung erforderlich</p><p className="mt-2 text-sm text-zinc-500">{error}</p></div>;

  return <div className="space-y-8">
    <section className="panel p-2"><div className="grid grid-cols-2 gap-2">{(["backtest", "live"] as const).map((value) => { const count = trades.filter((trade) => trade.trade_mode === value).length; return <button key={value} type="button" onClick={() => changeTradeMode(value)} className={`rounded-xl px-4 py-3 text-left transition ${tradeMode === value ? "bg-lime/10 text-lime ring-1 ring-lime/30" : "text-zinc-500 hover:bg-white/[0.02] hover:text-zinc-300"}`}><span className="block text-sm font-bold">{value === "backtest" ? "Backtests" : "Live Trades"}</span><span className="mt-1 block text-[10px] font-normal text-zinc-600">{count} {count === 1 ? "Eintrag" : "Einträge"}</span></button>; })}</div></section>

    <section><div className="mb-4 flex flex-col items-start gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold">{selected.length ? "Gefilterte Kennzahlen" : tradeMode === "live" ? "Live-Trade-Übersicht" : "Backtest-Übersicht"}</p><p className="mt-1 text-xs text-zinc-600">Wins und Losses folgen dem tatsächlichen R-Ergebnis. „Kein Trade“ wird separat gezählt.</p></div><p className="text-xs text-zinc-600">{filtered.length} von {modeTrades.length} Einträgen</p></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-6">
      <MetricCard label="Trades" value={String(stats.trades)} /><MetricCard label="Kein Trade" value={String(stats.noTrades)} /><MetricCard label="Wins" value={String(stats.wins)} tone="positive" /><MetricCard label="Losses" value={String(stats.losses)} tone="negative" /><MetricCard label="Break-even" value={String(stats.breakeven)} /><MetricCard label="Winrate" value={format(stats.winrate, "%")} /><MetricCard label="Ø R" value={format(stats.avgR, "R")} tone={stats.avgR > 0 ? "positive" : stats.avgR < 0 ? "negative" : "default"} />
      <MetricCard label="Gesamtes R" value={format(stats.totalR, "R")} tone={stats.totalR > 0 ? "positive" : stats.totalR < 0 ? "negative" : "default"} /><MetricCard label="Ø Gewinner" value={format(stats.avgWinner, "R")} /><MetricCard label="Ø Verlierer" value={format(stats.avgLoser, "R")} /><MetricCard label="Ø geplantes R:R" value={format(stats.avgPlannedRr)} /><MetricCard label="Profit Factor" value={pf(stats.profitFactor)} /><MetricCard label="Expectancy" value={format(stats.expectancy, "R")} />
    </div></section>

    <section className="panel overflow-hidden"><div className="border-b border-line px-4 py-4 sm:px-5"><p className="text-sm font-semibold">Einzelne Tags</p><p className="mt-1 text-xs text-zinc-600">Schneller Überblick über die bisherige Stichprobe.</p></div><div className="divide-y divide-line md:hidden">{tagStats.map(({ tag, stats: row }) => <article key={tag.id} className="p-4"><p className="font-semibold text-zinc-200">{tag.name}</p><div className="mt-4 grid grid-cols-3 gap-x-3 gap-y-4"><div><span className="label">Trades</span><p className="text-sm font-bold">{row.trades}</p></div><div><span className="label">Kein Trade</span><p className="text-sm font-bold">{row.noTrades}</p></div><div><span className="label">Winrate</span><p className="text-sm font-bold tabular-nums">{format(row.winrate, "%")}</p></div><div><span className="label">Ø R</span><p className="text-sm font-bold tabular-nums">{format(row.avgR, "R")}</p></div><div><span className="label">Gesamt</span><p className={`text-sm font-bold tabular-nums ${row.totalR > 0 ? "text-emerald-400" : row.totalR < 0 ? "text-rose-400" : ""}`}>{format(row.totalR, "R")}</p></div><div><span className="label">Profit Factor</span><p className="text-sm font-bold tabular-nums">{pf(row.profitFactor)}</p></div></div></article>)}{tagStats.length === 0 && <div className="px-4 py-12 text-center text-sm text-zinc-600">Noch keine Tag-Daten vorhanden.</div>}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left"><thead className="bg-ink/50 text-[10px] uppercase tracking-[0.13em] text-zinc-600"><tr><th className="px-5 py-3">Tag</th><th className="px-4 py-3">Trades</th><th className="px-4 py-3">Kein Trade</th><th className="px-4 py-3">Winrate</th><th className="px-4 py-3">Ø R</th><th className="px-4 py-3">Gesamtes R</th><th className="px-5 py-3">Profit Factor</th></tr></thead><tbody className="divide-y divide-line">{tagStats.map(({ tag, stats: row }) => <tr key={tag.id} className="text-sm"><td className="px-5 py-3 font-medium">{tag.name}</td><td className="px-4 py-3 text-zinc-400">{row.trades}</td><td className="px-4 py-3 text-zinc-400">{row.noTrades}</td><td className="px-4 py-3 tabular-nums text-zinc-400">{format(row.winrate, "%")}</td><td className="px-4 py-3 tabular-nums">{format(row.avgR, "R")}</td><td className={`px-4 py-3 tabular-nums ${row.totalR > 0 ? "text-emerald-400" : row.totalR < 0 ? "text-rose-400" : ""}`}>{format(row.totalR, "R")}</td><td className="px-5 py-3 tabular-nums text-zinc-400">{pf(row.profitFactor)}</td></tr>)}{tagStats.length === 0 && <tr><td colSpan={7} className="px-5 py-12 text-center text-sm text-zinc-600">Noch keine Tag-Daten vorhanden.</td></tr>}</tbody></table></div></section>

    <section className="panel overflow-hidden"><div className="flex flex-col items-start gap-2 border-b border-line px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><p className="flex items-center gap-2 text-sm font-semibold"><BookOpenText className="h-4 w-4 text-lime" /> Eigene Nachbetrachtungen</p><p className="mt-1 text-xs text-zinc-600">Die Auswahl folgt dem oben gesetzten Tag-Filter.</p></div><span className="text-xs text-zinc-600">{reviewedTrades.length} Einträge</span></div><div className="divide-y divide-line">{reviewedTrades.map((trade) => <article key={trade.id} className="p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-zinc-200">{trade.instrument} · {trade.result_type === "no_trade" ? "KEIN TRADE" : trade.direction?.toUpperCase() ?? "—"}</p><p className="mt-1 text-xs text-zinc-600">{new Intl.DateTimeFormat("de-DE").format(new Date(`${trade.trade_date}T12:00:00`))}{trade.result_r === null ? "" : ` · ${trade.result_r > 0 ? "+" : ""}${trade.result_r.toFixed(2)}R`}</p></div><Link href={`/trades/${trade.id}/bearbeiten`} className="flex min-h-11 items-center text-xs font-semibold text-lime hover:text-white">Bearbeiten</Link></div><div className="grid gap-4 lg:grid-cols-3">{trade.review_observation && <div><span className="label">Aufgefallen</span><p className="whitespace-pre-wrap text-sm leading-6 text-zinc-400">{trade.review_observation}</p></div>}{trade.result_type === "no_trade" ? trade.review_illogical && <div><span className="label">Unlogisch</span><p className="whitespace-pre-wrap text-sm leading-6 text-zinc-400">{trade.review_illogical}</p></div> : <>{trade.review_mistake && <div><span className="label">Missachtet</span><p className="whitespace-pre-wrap text-sm leading-6 text-zinc-400">{trade.review_mistake}</p></div>}{trade.review_invalidation && <div><span className="label">Entry entkräftet durch</span><p className="whitespace-pre-wrap text-sm leading-6 text-zinc-400">{trade.review_invalidation}</p></div>}</>}</div></article>)}{reviewedTrades.length === 0 && <div className="px-4 py-12 text-center text-sm text-zinc-600 sm:px-5">Für diese Auswahl wurden noch keine eigenen Nachbetrachtungen eingetragen.</div>}</div></section>

    <section className="panel p-4 sm:p-5"><div className="mb-4 flex flex-col items-start gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold">Auswertung nach Tags</p><p className="mt-1 text-xs text-zinc-600">Ein Trade muss alle gewählten Tags enthalten.</p></div>{selected.length > 0 && <button type="button" onClick={() => setSelected([])} className="min-h-11 text-xs text-zinc-500 hover:text-white">Auswahl leeren</button>}</div><TagChooser tags={tags} value={selected} onChange={setSelected} /></section>

    <section><div className="mb-4"><p className="text-sm font-semibold">Gruppenvergleich</p><p className="mt-1 text-xs text-zinc-600">Prüfen Sie, ob eine zusätzliche Confluence messbaren Mehrwert liefert.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr]">
      <div className="panel p-4 sm:p-5"><span className="mb-1 block text-[10px] font-bold uppercase tracking-[0.18em] text-lime">Gruppe A</span><p className="mb-4 text-xs text-zinc-600">{groupA.length ? `${groupA.length} Tags kombiniert` : tradeMode === "live" ? "Alle Live Trades" : "Alle Backtests"}</p><TagChooser tags={tags} value={groupA} onChange={setGroupA} /><div className="my-5 border-t border-line" /><ComparisonStats stats={statsA} /></div>
      <div className="hidden items-center lg:flex"><ArrowRight className="h-5 w-5 text-zinc-700" /></div>
      <div className="panel p-4 sm:p-5"><span className="mb-1 block text-[10px] font-bold uppercase tracking-[0.18em] text-lime">Gruppe B</span><p className="mb-4 text-xs text-zinc-600">{groupB.length ? `${groupB.length} Tags kombiniert` : tradeMode === "live" ? "Alle Live Trades" : "Alle Backtests"}</p><TagChooser tags={tags} value={groupB} onChange={setGroupB} /><div className="my-5 border-t border-line" /><ComparisonStats stats={statsB} /></div>
    </div></section>
  </div>;
}
